# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				big_dropper = true
				furnace = true
				fish_tank = true
				dropper = true
				sign = true
				potion_pad = true
				smoker = true
				big_dispenser = true
				campfire = true
				equipment_stand = true
				chest = true
				sculk_shrieker = true
				enchanting_table = true
				structure_block = true
				sculk_catalyst = true
				bell = true
				end_gateway = true
				command_block = true
				beacon = true
				jigsaw = true
				big_barrel = true
				mob_spawner = true
				blast_furnace = true
				pedestal = true
				flag = true
				daylight_detector = true
				jukebox = true
				brewing_stand = true
				sculk_sensor = true
				entangled_scaffolding = true
				beehive = true
				conduit = true
				creative_barrel = true
				dispenser = true
				warp_block = true
				lectern = true
				couriporter = true
				skull = true
				barrel = true
				piston = true
				end_portal = true
				shulker_box = true
				banner = true
				ender_chest = true
				comparator = true
				redstone_trigger = true
				hopper = true
				trapped_chest = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.immersive_weathering]
				icicle = true

			[light_sources.settings.block_entities.supplementaries]
				pedestal = true
				clock_block = true
				wall_lantern = true
				blackboard = true
				flag = true
				sack = true
				speaker_block = true
				key_lockable_tile = true
				bubble_block = true
				bellows = true
				notice_board = true
				skull_pile = true
				ceiling_banner = true
				jar_boat = true
				cage = true
				skull_candle = true
				bamboo_spikes = true
				hanging_sign_oak = true
				trapped_present = true
				hourglass = true
				wind_vane = true
				doormat = true
				jar = true
				spring_launcher_arm = true
				item_shelf = true
				turn_table = true
				faucet = true
				structure_temp = true
				block_generator = true
				book_pile = true
				rope_knot = true
				hanging_flower_pot = true
				statue = true
				goblet = true
				urn = true
				flower_box = true
				pulley_block = true
				globe = true
				timber_frame = true
				safe = true
				present = true
				sign_post = true

			[light_sources.settings.block_entities.wilderwild]
				termite_mound = true
				hanging_tendril = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				falling_icicle = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				falling_ash = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				falling_sand_layer = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				falling_propagule = true
				skeleton = true
				falling_leaf_layer = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.campanion]
				lawn_chair = true
				grappling_hook = true
				iron_spear = true

			[light_sources.settings.entities.blasttravel]
				cannon = true

			[light_sources.settings.entities.snowyspirit]
				sled = true

			[light_sources.settings.entities.whipdashing]
				hook_entity = true

			[light_sources.settings.entities.halfdoors]
				tiny_door = true
				door_saw = true

			[light_sources.settings.entities.luggage]
				luggage = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				gyrodyne = true
				biplane = true

			[light_sources.settings.entities.peculiarpieces]
				teleport_item_entity = true
				equipment_stand_entity = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				falling_ash = true
				falling_lantern = true
				falling_urn = true
				brick_projectile = true
				pearl_marker = true
				falling_sack = true
				red_merchant = true
				bomb = true
				rope_arrow = true

			[light_sources.settings.entities.wilderwild]
				firefly = true
				jellyfish = true
				ancient_horn_projectile = true

			[light_sources.settings.entities.enchancement]
				brimstone = true
				ice_shard = true
				grapple_fishing_bobber = true

			[light_sources.settings.entities.kahur]
				kahur_shot = true

