enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
glassdoor = true
chalk = true
everycomp = true
spelunkery = true
farmersdelight = true
snowyspirit = true
supplementaries = true
windchimes = true
aurorasdeco = true
tradingpost = true
harvestseason = true
immersive_weathering = true
pyrotastic = true
wilderwild = true
yttr = true
netherchest = true
snowrealmagic = true
drg_flares = true
moyai = true
architects_palette = true
minecraft = true
soul_vitric = true
comforts = true
